from pathlib import Path
import ast
import hashlib
import json
import sys

version = sys.argv[1]
assert version == "33.02"
app_path = Path("payload/app.py")
text = app_path.read_text(encoding="utf-8-sig")

def replace_once(old, new):
    global text
    assert text.count(old) == 1, (old[:180], text.count(old))
    text = text.replace(old, new, 1)

replace_once('APP_VERSION = "33.01"', 'APP_VERSION = "33.02"')

# Ask the already-running yt-dlp extraction for its selected video/audio sizes
# and emit machine-readable progress. This adds no second metadata request.
replace_once(
    '''        "--print",
        "before_dl:__VD_TITLE__%(title)s",

        # Exact final file path after merge/post-processing.
''',
    '''        "--print",
        "before_dl:__VD_TITLE__%(title)s",
        "--print",
        "before_dl:__VD_FORMATS__%(requested_formats)j",
        "--progress-template",
        "download:__VD_PROGRESS__%(info.format_id)s|%(progress.downloaded_bytes)s|%(progress.total_bytes)s|%(progress.total_bytes_estimate)s|%(progress.speed)s",

        # Exact final file path after merge/post-processing.
''',
)

replace_once(
    '''    progress_stream_totals = {}
''',
    '''    progress_stream_totals = {}

    # V33.02: one authoritative byte timeline across separate video/audio
    # downloads. The selected formats marker supplies the final combined size
    # before transfer; machine progress supplies cumulative bytes per stream.
    unified_total_bytes = 0
    unified_phase_id = ""
    unified_phase_downloaded = {}
    unified_last_bytes = 0
    unified_last_wall = None
    unified_speed_ema = None

''',
)

marker = '''            # Title marker generated by --print before_dl.
            if line.startswith("__VD_TITLE__"):
'''
injected = '''            # Selected video/audio formats from the same extraction. Their
            # combined size remains fixed throughout the download.
            if line.startswith("__VD_FORMATS__"):
                try:
                    formats = json.loads(line[len("__VD_FORMATS__"):].strip())
                    if isinstance(formats, dict):
                        formats = [formats]
                    total = 0
                    for item in formats if isinstance(formats, list) else []:
                        if not isinstance(item, dict):
                            continue
                        value = item.get("filesize") or item.get("filesize_approx") or 0
                        try:
                            total += max(0, int(float(value)))
                        except Exception:
                            pass
                    if total > 0:
                        unified_total_bytes = total
                        if stats_callback:
                            stats_callback(size=_human_file_size(total))
                except Exception as exc:
                    log((f"[{job_label}] " if job_label else "") + "Size metadata warning: " + str(exc))
                continue

            # Machine-readable progress is converted to a single monotonic
            # byte count, sustained speed and ETA across video + audio.
            if line.startswith("__VD_PROGRESS__"):
                try:
                    fields = line[len("__VD_PROGRESS__"):].split("|")
                    while len(fields) < 5:
                        fields.append("")
                    phase_id = fields[0].strip() or "stream"

                    def _metric_number(value):
                        try:
                            return max(0.0, float(str(value).strip()))
                        except Exception:
                            return 0.0

                    downloaded = _metric_number(fields[1])
                    phase_total = _metric_number(fields[2]) or _metric_number(fields[3])
                    if phase_total > 0:
                        progress_stream_totals[phase_id] = int(phase_total)
                    unified_phase_downloaded[phase_id] = max(
                        float(unified_phase_downloaded.get(phase_id, 0.0)),
                        downloaded,
                    )
                    unified_phase_id = phase_id
                    global_downloaded = int(sum(unified_phase_downloaded.values()))
                    now = time.perf_counter()
                    if unified_last_wall is not None and now > unified_last_wall:
                        delta = max(0, global_downloaded - unified_last_bytes)
                        elapsed = now - unified_last_wall
                        if delta > 0 and elapsed >= 0.15:
                            sample = delta / elapsed
                            unified_speed_ema = (
                                sample if unified_speed_ema is None
                                else unified_speed_ema + 0.18 * (sample - unified_speed_ema)
                            )
                    unified_last_bytes = max(unified_last_bytes, global_downloaded)
                    unified_last_wall = now

                    known_total = unified_total_bytes or sum(progress_stream_totals.values())
                    percent = None
                    eta_text = None
                    if known_total > 0:
                        percent = min(99.0, global_downloaded * 100.0 / known_total)
                        if unified_speed_ema and unified_speed_ema > 0:
                            eta_text = seconds_to_eta(
                                max(0, known_total - global_downloaded) / unified_speed_ema
                            )
                    speed_text = (
                        bytes_to_human(unified_speed_ema) + "/s"
                        if unified_speed_ema and unified_speed_ema > 0
                        else None
                    )
                    size_text = _human_file_size(known_total) if known_total > 0 else None
                    if percent is not None and progress_callback:
                        progress_callback(percent)
                    if stats_callback:
                        stats_callback(
                            percent=percent,
                            speed=speed_text,
                            eta=eta_text,
                            size=size_text,
                        )
                except Exception as exc:
                    log((f"[{job_label}] " if job_label else "") + "Unified progress warning: " + str(exc))
                continue

            # Title marker generated by --print before_dl.
            if line.startswith("__VD_TITLE__"):
'''
replace_once(marker, injected)

ast.parse(text)
app_path.write_text(text, encoding="utf-8")
app_hash = hashlib.sha256(app_path.read_bytes()).hexdigest()
manifest_path = Path("payload/update_manifest.json")
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
manifest["version"] = version
manifest["created_by"] = (
    "v33.02 unifies video and audio byte progress, locks the selected final "
    "size before transfer, and derives sustained speed and ETA from real bytes"
)
manifest["files"][0]["sha256"] = app_hash
manifest["files"][0]["size"] = app_path.stat().st_size
manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
print("VERIFIED v33.02 app.py sha256", app_hash)
